# update to latest
- homebrew: update_homebrew=yes

- name:  install {{item}}
  homebrew_tap: tap="{{item}}" state=present
  with_items:
    - homebrew/cask-versions
    - homebrew/cask-fonts

- name: install {{item}}
  homebrew: name={{item}} state=present
  with_items:
    - fish
    - git
    - curl
    - jq
    - tree
    - peco
    - ghq
    - hub
    - colordiff
    - ansible
    - wget
    - vim
    - tig
    - exa
    - bat
    - fd
    - sd
    - procs
    - ripgrep
    - tmux
    - mint # Swift製コマンドラインツールのパッケージ管理ツール
    - carthage
    - rbenv
    - nodebrew
    - rename

- name: install {{item}}
  homebrew_cask: name={{item}} state=present
  environment:
    HOMEBREW_CASK_OPTS: --appdir=/Applications
  with_items:
    - alfred
    - rectangle # 画面分割アプリ
    - google-japanese-ime
    - google-chrome
    - firefox
    - visual-studio-code
    - iterm2
    - slack
    - tweetbot
    - kindle
    - 1password
    - jetbrains-toolbox
    - dash
    - docker
    - charles
    - font-fira-code

# upgrade homebrew tasks to latest
- name: upgrade homebrew
  homebrew: update_homebrew=yes upgrade_all=yes

